apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: {{ required "email is required" .Values.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: {{ required "cfEmail is required" .Values.cfEmail | quote }}
          apiTokenSecretRef:
            name: {{ .Values.secretName }}
            key: {{ .Values.secretKey }}
---
apiVersion: v1
data:
  api-token: {{ required "cfApiToken is required" .Values.cfApiToken | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
