{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 51820
      targetPort: udp-vpn
      protocol: UDP
      name: udp-vpn
    - port: 51821
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
{{- end }}