{{- if .Values.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wg-easy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "wg-easy.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wg-easy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wg-easy.selectorLabels" . | nindent 8 }}
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "wg-easy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.volume.enabled }}
      volumes:
        - name: wireguard-volume
          persistentVolumeClaim:
            claimName: {{ include "wg-easy.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "wg-easy.wg-easyVersion" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: udp-vpn
              containerPort: 51820
              protocol: UDP
            - name: http-ui
              containerPort: 51821
              protocol: TCP
          {{- if .Values.volume.enabled }}
          volumeMounts:
            - mountPath: "/etc/wireguard"
              name: wireguard-volume
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheckUrl | quote }}
              port: http-ui
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheckUrl | quote }}
              port: http-ui
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.environmentVariables }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.enableHttpOpenTelemetryCollector }}
          - name: COLLECTOR_OTLP_ENABLED
            value: "true"
          {{- end }}  
          {{- if .Values.enableHttpZipkinCollector }}
          - name: COLLECTOR_ZIPKIN_HOST_PORT
            value: ":9411"
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
