# Default values for wg-easy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/wg-easy/wg-easy
  tag: 14
  pullPolicy: IfNotPresent


# kubectl create secret generic wg-ui-password --from-literal=webpassword=password
web:
  # Set password.secretName if you want to set a web password
  password:
    secretName: "wg-ui-password"
  service:
    type: ClusterIP
    # Modify this port when wishing to change the web port the UI is accessible through
    port: 51821
    # This port value should likely not be changed since wg-easy is hard coded to 51821
    targetPort: 51821
    annotations: {}

wireguard:
  service:
    type: ClusterIP
    # Modify this port when wishing to change the service port systems connect to
    port: 51820
    # This port value should likely not be changed since wg-easy iptables dport is hard coded to 51820
    targetPort: 51820
    annotations: {}

  # Wireguard host is required and used when creating client config
  host: "wge.example.com"
  clientAddrRange: 10.177.0.x
  dns: 1.1.1.1
  allowedIps: "0.0.0.0/0, ::/0"
  persistentKeepalive: 0
  #mtu: 1420
  #postUp: |-
    # Put Wireguard post up commands here, here per line
  #postDown: |-
    # Put Wireguard post down commands here, here per line

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: wge.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: wg-easy-tls
     hosts:
       - wge.example.com

persistence:
  enabled: false
  size: 100Mi
  annotations: {}
  # storageClass: ""
  accessModes:
    - ReadWriteOnce
  subPath: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
